### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by BlackOsint** [sasauz/kibana_vis_gantt#1]
I follow the instructions, but i have a log error with no package.json

**Comment by sasauz** [comment]
Sorry it was my fold. You should copy gantt_vis (NOT kibana_vis_gantt) in **KIBANA_HOME/plugins**
I've edit it in description

**Comment by sasauz** [comment]
I've figure out that via web interface it is possible to upload only 100 files. Now is the plugin completely in github and it should work.

**Comment by BlackOsint** [comment]
Ok thanks
