### ISSUE TITLE
Not Seeing the Gantt Chart with my data

### ISSUE THREAD

**Issue by lnwiese** [sasauz/kibana_vis_gantt#3]
I successfully added the plugin and tried to use two date fields as the start and end buckets. I made sure to mess around with the intervals, but was unable to see any visual. Below are 3 rows of the mock data I am using. (Note: I am running kibana 5.5.3 and elassandra 5.5.0.4)

![screenshot from 2017-11-14 16-18-11](https://user-images.githubusercontent.com/33288037/32811994-8c8f2fd2-c957-11e7-8d02-1bcf36a7ad84.png)

The start_date and end_date were used as my start and end buckets. Those two fields are acting as date types that can function with Kibana's time filtering too. Let me know if you need anymore information and thanks in advance!

Liam

**Comment by sasauz** [comment]
Hello Liam,

did you also define Item and Group By? For example you can take buzzword as Item and state field as Group By. Or state field for both (Item and Group By).

In actual version of plugin you should define Item and group by. I will change it in next versions, so that you will be able to define only start and end date without items and group by.

I hope it will be helpful for your case.

Aleks

**Comment by lnwiese** [comment]
Yes I did try different combinations for both Item and Group By: I tried using the item and state as your example. This is the set up I had:

![image](https://user-images.githubusercontent.com/33288037/32898703-b6a5816c-ca9d-11e7-8d5f-9d8274af9b8e.png) ![image](https://user-images.githubusercontent.com/33288037/32898654-9329f8bc-ca9d-11e7-9eca-cdbf616f08c3.png) ![image](https://user-images.githubusercontent.com/33288037/32898746-d61d5812-ca9d-11e7-8860-9139fba2af77.png)

No visual still. I realized I misspoke, the start_date and end_date aren't exactly type date but are timestamp more specifically when I created the table in elassandra. As well the start_date type is mapped to the strict_date_time format.

![image](https://user-images.githubusercontent.com/33288037/32899239-44f0beae-ca9f-11e7-9179-fa3398b34db0.png)

I went back to make both fields strict_date_time format as well as none of them being strict and neither way worked. I recreated the table to label those columns as date (instead of timestamp) and that did not work either.

**Comment by sasauz** [comment]
Hello Liam,

I've found the problem. In the last update I've added new feauters such as autoresize and flexible heigth. And they have wrong default values. You can set autoresize and heigh to 0 and then you will see gantt with your data. Or you can download new version of plugin and reinstall it. (how to do it you will find in plugin description)

Please let me know if it solved your problem.

**Comment by sasauz** [comment]
One more things. Your item duration is in days with start at 08:00. If you want to show data correctly you should choose days or hours as interval in start and end buckets. If you select interval monthly then elasticsearch will agregate all your data and you will see wrong gantt chart.
