### ISSUE TITLE
Not seeing visualization type Gantt

### ISSUE THREAD

**Issue by prKrumm** [sasauz/kibana_vis_gantt#4]
Hi,

as shown below I only see the standard Visualization types.
kibana_vis_gantt is in plugins folder.

![image](https://user-images.githubusercontent.com/18287576/33030856-bd4eb024-ce1c-11e7-882e-e01fbd4ddab3.png)

**Comment by sasauz** [comment]
Hi,

what kind Kibana Version do you have? If your version is not 5.6.1, you should change the version in gantt_vis/package.json file. 
![image](https://user-images.githubusercontent.com/897489/33031751-76cd34b0-ce1f-11e7-8160-09163aaa414b.png)
For example if your Kibana version is 5.6.3 then you should write `"version": "5.6.3"
`
Did you install plugin like in description?

**Comment by prKrumm** [comment]
It works! Thanks! Do you support version 6.0.0?

**Comment by sasauz** [comment]
You are welcome! :) I've didn't try it in version 6.0.0, but I will do it next 3 weeks.
